version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    container_name: auto_approve_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - OWNER_ID=${OWNER_ID}
      - MONGO_URI=mongodb://mongo:27017/AutoApproveBot
      - MAX_APPROVALS_PER_SECOND=25
      - LOG_LEVEL=INFO
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    container_name: auto_approve_mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

